run:
  concurrency: 4
  deadline: 10m

  skip-dirs:
  - pkg/client/core
  - pkg/client/extensions
  - pkg/client/settings

  skip-files:
  - ".*\\.pb\\.go$"

linters:
  disable:
  - unused

issues:
  exclude-rules:
  - linters:
    - staticcheck
    text: "SA1019:" # Excludes messages where deprecated variables are used
